# Generated by Django 3.0.6 on 2022-10-24 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0002_auto_20221024_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solitransporte',
            options={},
        ),
        migrations.RemoveField(
            model_name='solitransporte',
            name='cantidad_actual',
        ),
        migrations.RemoveField(
            model_name='solitransporte',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='solitransporte',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='solitransporte',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='solitransporte',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='solitransporte',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='solitransporte',
            name='productor',
        ),
        migrations.RemoveField(
            model_name='solitransporte',
            name='refrigeracion',
        ),
        migrations.RemoveField(
            model_name='solitransporte',
            name='tamaño',
        ),
        migrations.RemoveField(
            model_name='solitransporte',
            name='transportista',
        ),
        migrations.RemoveField(
            model_name='solitransporte',
            name='variedad',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='solitransporte',
            name='soli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feriavirtualapp.Post'),
        ),
        migrations.AddField(
            model_name='solitransporte',
            name='transporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feriavirtualapp.Transporte'),
        ),
    ]
