# Generated by Django 3.0.6 on 2022-11-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0004_auto_20221103_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(default='Perfil/default.png', upload_to='Perfil'),
        ),
    ]
