# Generated by Django 3.0.6 on 2022-11-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0006_auto_20221106_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Codigopostal',
            new_name='codigopostal',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='post',
            name='refrigeracion',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='soliTransporte',
        ),
    ]
