# Generated by Django 3.0.6 on 2022-11-06 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0007_auto_20221106_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='transportista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportista', to=settings.AUTH_USER_MODEL),
        ),
    ]
