# Generated by Django 3.0.6 on 2022-11-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0008_post_transportista'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentariosTransportista',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='EstadoSolicitud',
            field=models.CharField(choices=[('1', 'Aprobado'), ('2', 'Rechazado'), ('3', 'Pendiente'), ('4', 'Subasta Transporte'), ('5', 'Esperando productos en bodega central'), ('6', 'Revision de calidad'), ('7', 'En camino'), ('8', 'Viaje interrumpido'), ('9', 'Destino'), ('10', 'Rechazado'), ('11', 'Saldo')], default='3', max_length=50, null=True),
        ),
    ]
