# Generated by Django 3.0.6 on 2022-11-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0009_auto_20221106_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='EstadoSolicitud',
            field=models.CharField(choices=[('1', 'Aprobado'), ('2', 'Rechazado'), ('3', 'Pendiente'), ('4', 'Subasta Transporte'), ('5', 'Esperando productos en bodega central'), ('6', 'Revision de calidad'), ('7', 'Revisado'), ('8', 'En camino'), ('9', 'Viaje interrumpido'), ('10', 'Destino'), ('11', 'Rechazado'), ('12', 'Saldo')], default='3', max_length=50, null=True),
        ),
    ]
