# Generated by Django 3.0.6 on 2022-11-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0010_auto_20221107_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
