# Generated by Django 3.0.6 on 2022-11-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0012_auto_20221107_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='EstadoSolicitud',
            field=models.CharField(choices=[('1', 'Aprobado'), ('2', 'Rechazado'), ('3', 'Pendiente'), ('4', 'Subasta de transporte'), ('5', 'Transporte listo'), ('6', 'Entregado en bodega'), ('7', 'Revision de calidad'), ('8', 'Rechazado en revision'), ('9', 'Revisado'), ('10', 'En camino'), ('11', 'Viaje interrumpido'), ('12', 'Destino'), ('13', 'Aceptado por el destinatario'), ('14', 'Rechazado por el destinatario'), ('15', 'Saldo')], default='3', max_length=50, null=True),
        ),
    ]
