# Generated by Django 3.0.6 on 2022-11-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0014_posthistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthistorico',
            name='cantidad_actual',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='posthistorico',
            name='cantidad_necesaria',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
