# Generated by Django 3.0.6 on 2022-11-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0016_auto_20221108_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
