# Generated by Django 3.0.6 on 2022-11-08 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0017_transporte_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesoventa',
            name='from_post',
        ),
        migrations.RemoveField(
            model_name='procesoventa',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='procesoventa',
            name='to_user',
        ),
        migrations.AddField(
            model_name='post',
            name='transporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporte', to='feriavirtualapp.Transporte'),
        ),
        migrations.AddField(
            model_name='posthistorico',
            name='transporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporteh', to='feriavirtualapp.Transporte'),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='ProcesoVenta',
        ),
    ]
